#!/usr/bin/env python3
"""
Normaliza los títulos H1 de todos los archivos de contenido
para que coincidan con los títulos del índice en español.
"""
import os

BASE = "/home/adamshlomo/leyendas-judios/output"

TITULOS = {

# ════════════════════════════════════════════════════════
# VOL 1
# ════════════════════════════════════════════════════════
"vol1/seccion-011-the-first-things-created.md":              "Las primeras cosas creadas",
"vol1/seccion-012-the-alphabet.md":                          "El alfabeto",
"vol1/seccion-013-the-first-day.md":                         "El primer día",
"vol1/seccion-014-the-second-day.md":                        "El segundo día",
"vol1/seccion-015-the-third-day.md":                         "El tercer día",
"vol1/seccion-016-the-fourth-day.md":                        "El cuarto día",
"vol1/seccion-017-the-fifth-day.md":                         "El quinto día",
"vol1/seccion-018-the-sixth-day.md":                         "El sexto día",
"vol1/seccion-019-all-things-praise-the-lord.md":            "Todas las cosas alaban al Eterno",
"vol1/seccion-020-man-and-the-world.md":                     "El hombre y el mundo",
"vol1/seccion-021-the-angels-and-the-creation-of-man.md":   "Los ángeles y la creación del hombre",
"vol1/seccion-022-the-creation-of-adam.md":                  "La creación de Adam",
"vol1/seccion-023-the-soul-of-man.md":                       "El alma del hombre",
"vol1/seccion-024-the-ideal-man.md":                         "El hombre ideal",
"vol1/seccion-025-the-fall-of-satan.md":                     "La caída de Satán",
"vol1/seccion-026-woman.md":                                  "La mujer",
"vol1/seccion-027-adam-and-eve-in-paradise.md":              "Adam y Javá en el Paraíso",
"vol1/seccion-028-the-fall-of-man.md":                       "La caída del hombre",
"vol1/seccion-029-the-punishment.md":                        "El castigo",
"vol1/seccion-030-sabbath-in-heaven.md":                     "Shabat en el cielo",
"vol1/seccion-031-adams-repentance.md":                      "El arrepentimiento de Adam",
"vol1/seccion-032-the-book-of-raziel.md":                    "El libro de Raziel",
"vol1/seccion-033-the-sickness-of-adam.md":                  "La enfermedad de Adam",
"vol1/seccion-034-eves-story-of-the-fall.md":                "El relato de Javá sobre la caída",
"vol1/seccion-035-the-death-of-adam.md":                     "La muerte de Adam",
"vol1/seccion-036-the-death-of-eve.md":                      "La muerte de Javá",
"vol1/seccion-037-the-birth-of-cain.md":                     "El nacimiento de Caín",
"vol1/seccion-038-fratricide.md":                            "El fratricidio",
"vol1/seccion-039-the-punishment-of-cain.md":                "El castigo de Caín",
"vol1/seccion-040-the-inhabitants-of-the-seven-earths.md":   "Los habitantes de las siete tierras",
"vol1/seccion-041-the-descendants-of-cain.md":               "Los descendientes de Caín",
"vol1/seccion-042-the-descendants-of-adam-and-lilith.md":    "Los descendientes de Adán y Lilit",
"vol1/seccion-043-seth-and-his-descendants.md":              "Set y sus descendientes",
"vol1/seccion-044-enosh.md":                                  "Enós",
"vol1/seccion-045-the-fall-of-the-angels.md":                "La caída de los ángeles",
"vol1/seccion-046-enoch-ruler-and-teacher.md":               "Enoc, gobernante y maestro",
"vol1/seccion-047-the-ascension-of-enoch.md":                "La ascensión de Enoc",
"vol1/seccion-048-the-translation-of-enoch.md":              "La traslación de Enoc",
"vol1/seccion-049-methuselah.md":                            "Matusalén",
"vol1/seccion-050-the-birth-of-noah.md":                     "El nacimiento de Nóaj",
"vol1/seccion-051-the-punishment-of-the-fallen-angels.md":   "El castigo de los ángeles caídos",
"vol1/seccion-052-the-generation-of-the-deluge.md":          "La generación del Diluvio",
"vol1/seccion-053-the-holy-book.md":                         "El Libro Sagrado",
"vol1/seccion-054-the-inmates-of-the-ark.md":                "Los moradores del Arca",
"vol1/seccion-055-the-flood.md":                             "El Diluvio",
"vol1/seccion-056-noah-leaves-the-ark.md":                   "Nóaj abandona el Arca",
"vol1/seccion-057-the-curse-of-drunkenness.md":              "La maldición de la embriaguez",
"vol1/seccion-058-noahs-descendants-spread-abroad.md":       "Los descendientes de Nóaj se dispersan por el mundo",
"vol1/seccion-059-the-depravity-of-mankind.md":              "La depravación de la humanidad",
"vol1/seccion-060-nimrod.md":                                 "Nimrod",
"vol1/seccion-061-the-tower-of-babel.md":                    "La Torre de Babel",
"vol1/seccion-062-the-wicked-generations.md":                "Las generaciones perversas",
"vol1/seccion-063-the-birth-of-abraham.md":                  "El nacimiento de Avraham",
"vol1/seccion-064-the-babe-proclaims-god.md":                "El niño reconoce al Eterno",
"vol1/seccion-065-abrahams-first-appearance-in-public.md":   "La primera aparición pública de Avraham",
"vol1/seccion-066-the-preacher-of-the-true-faith.md":        "El predicador de la fe verdadera",
"vol1/seccion-067-in-the-fiery-furnace.md":                  "En el horno ardiente",
"vol1/seccion-068-abraham-emigrates-to-haran.md":            "Avraham emigra a Jarán",
"vol1/seccion-069-the-star-in-the-east.md":                  "La estrella en el oriente",
"vol1/seccion-070-the-true-believer.md":                     "El verdadero creyente",
"vol1/seccion-071-the-iconoclast.md":                        "El iconoclasta",
"vol1/seccion-072-abraham-in-canaan.md":                     "Avraham en Canaán",
"vol1/seccion-073-his-sojourn-in-egypt.md":                  "Su estancia en Egipto",
"vol1/seccion-074-the-first-pharaoh.md":                     "El primer faraón",
"vol1/seccion-075-the-war-of-the-kings.md":                  "La guerra de los reyes",
"vol1/seccion-076-the-covenant-of-the-pieces.md":            "El pacto entre las piezas",
"vol1/seccion-077-the-birth-of-ishmael.md":                  "El nacimiento de Ishmael",
"vol1/seccion-078-the-visit-of-the-angels.md":               "La visita de los ángeles",
"vol1/seccion-079-the-cities-of-sin.md":                     "Las ciudades del pecado",
"vol1/seccion-080-abraham-pleads-for-the-sinners.md":        "Avraham intercede por los pecadores",
"vol1/seccion-081-the-destruction-of-the-sinful-cities.md":  "La destrucción de las ciudades pecadoras",
"vol1/seccion-082-among-the-philistines.md":                 "Entre los filisteos",
"vol1/seccion-083-the-birth-of-isaac.md":                    "El nacimiento de Itzjak",
"vol1/seccion-084-ishmael-cast-off.md":                      "La expulsión de Ishmael",
"vol1/seccion-085-the-two-wives-of-ishmael.md":              "Las dos esposas de Ishmael",
"vol1/seccion-086-the-covenant-with-abimelech.md":           "El pacto con Avimélek",
"vol1/seccion-087-satan-accuses-abraham.md":                  "Satán acusa a Avraham",
"vol1/seccion-088-the-journey-to-moriah.md":                 "El camino hacia Moriá",
"vol1/seccion-089-the-akedah.md":                            "La Akedá",
"vol1/seccion-090-the-death-and-burial-of-sarah.md":         "La muerte y sepultura de Sará",
"vol1/seccion-091-eliezers-mission.md":                      "La misión de Eliézer",
"vol1/seccion-092-the-wooing-of-rebekah.md":                 "El cortejo de Rivká",
"vol1/seccion-093-the-last-years-of-abraham.md":             "Los últimos años de Avraham",
"vol1/seccion-094-a-herald-of-death.md":                     "Un heraldo de la muerte",
"vol1/seccion-095-abraham-views-earth-and-heaven.md":        "Avraham contempla la tierra y el cielo",
"vol1/seccion-096-the-patron-of-hebron.md":                  "El patrono de Hebrón",
"vol1/seccion-097-the-birth-of-esau-and-jacob.md":           "El nacimiento de Esav y Yaakov",
"vol1/seccion-098-the-favorite-of-abraham.md":               "El favorito de Avraham",
"vol1/seccion-099-the-sale-of-the-birthright.md":            "La venta de la primogenitura",
"vol1/seccion-100-isaac-with-the-philistines.md":            "Itzjak entre los filisteos",
"vol1/seccion-101-isaac-blesses-jacob.md":                   "Itzjak bendice a Yaakov",
"vol1/seccion-102-esaus-true-character-revealed.md":         "El verdadero carácter de Esav al descubierto",
"vol1/seccion-103-jacob-leaves-his-fathers-house.md":        "Yaakov abandona la casa de su padre",
"vol1/seccion-104-jacob-pursued-by-eliphaz-and-esau.md":     "Yaakov perseguido por Elifaz y Esav",
"vol1/seccion-105-the-day-of-miracles.md":                   "El día de los milagros",
"vol1/seccion-106-jacob-with-laban.md":                      "Yaakov con Laván",
"vol1/seccion-107-the-marriage-of-jacob.md":                 "El matrimonio de Yaakov",
"vol1/seccion-108-the-birth-of-jacobs-children.md":          "El nacimiento de los hijos de Yaakov",
"vol1/seccion-109-jacob-flees-before-laban.md":              "Yaakov huye de Laván",
"vol1/seccion-110-the-covenant-with-laban.md":               "El pacto con Laván",
"vol1/seccion-111-jacob-and-esau-prepare-to-meet.md":        "Yaakov y Esav se preparan para el encuentro",
"vol1/seccion-112-jacob-wrestles-with-the-angel.md":         "Yaakov lucha con el ángel",
"vol1/seccion-113-the-meeting-between-esau-and-jacob.md":    "El encuentro entre Esav y Yaakov",
"vol1/seccion-114-the-outrage-at-shechem.md":                "La afrenta de Shjem",
"vol1/seccion-115-a-war-frustrated.md":                      "Una guerra frustrada",
"vol1/seccion-116-the-war-with-the-ninevites.md":            "La guerra con los ninivitas",
"vol1/seccion-117-the-war-with-the-amorites.md":             "La guerra con los amorreos",
"vol1/seccion-118-isaac-blesses-levi-and-judah.md":          "Itzjak bendice a Leví y a Yehudá",
"vol1/seccion-119-joy-and-sorrow-in-the-house-of-jacob.md":  "Gozo y aflicción en la casa de Yaakov",
"vol1/seccion-120-esaus-campaign-against-jacob.md":          "La campaña de Esav contra Yaakov",
"vol1/seccion-121-the-descendants-of-esau.md":               "Los descendientes de Esav",

# ════════════════════════════════════════════════════════
# VOL 2
# ════════════════════════════════════════════════════════
"vol2/seccion-008-the-favorite-son.md":                              "El hijo predilecto",
"vol2/seccion-009-joseph-hated-by-his-brethren.md":                  "Yosef, odiado por sus hermanos",
"vol2/seccion-010-joseph-cast-into-the-pit.md":                      "Yosef arrojado al pozo",
"vol2/seccion-011-the-sale.md":                                       "La venta",
"vol2/seccion-012-josephs-three-masters.md":                         "Los tres amos de Yosef",
"vol2/seccion-013-josephs-coat-brought-to-his-father.md":            "La túnica de Yosef llevada ante su padre",
"vol2/seccion-014-judah-and-his-sons.md":                            "Yehudá y sus hijos",
"vol2/seccion-015-the-wives-of-the-sons-of-jacob.md":                "Las esposas de los hijos de Yaakov",
"vol2/seccion-016-joseph-the-slave-of-potiphar.md":                  "Yosef, esclavo de Potifar",
"vol2/seccion-017-joseph-and-zuleika.md":                            "Yosef y Zuleiká",
"vol2/seccion-018-joseph-resists-temptation.md":                     "Yosef resiste la tentación",
"vol2/seccion-019-joseph-in-prison.md":                              "Yosef en prisión",
"vol2/seccion-020-pharaohs-dreams.md":                               "Los sueños del Faraón",
"vol2/seccion-021-joseph-before-pharaoh.md":                         "Yosef ante el Faraón",
"vol2/seccion-022-the-ruler-of-egypt.md":                            "El gobernante de Egipto",
"vol2/seccion-023-josephs-brethren-in-egypt.md":                     "Los hermanos de Yosef en Egipto",
"vol2/seccion-024-joseph-meets-his-brethren.md":                     "Yosef se encuentra con sus hermanos",
"vol2/seccion-025-the-second-journey-to-egypt.md":                   "El segundo viaje a Egipto",
"vol2/seccion-026-joseph-and-benjamin.md":                           "Yosef y Binyamín",
"vol2/seccion-027-the-thief-caught.md":                              "El ladrón atrapado",
"vol2/seccion-028-judah-pleads-and-threatens.md":                    "Yehudá suplica y amenaza",
"vol2/seccion-029-joseph-makes-himself-known.md":                    "Yosef se da a conocer",
"vol2/seccion-030-jacob-receives-the-glad-tidings.md":               "Yaakov recibe las gratas nuevas",
"vol2/seccion-031-jacob-arrives-in-egypt.md":                        "Yaakov llega a Egipto",
"vol2/seccion-032-josephs-kindness-and-generosity.md":               "La bondad y la generosidad de Yosef",
"vol2/seccion-033-jacobs-last-wish.md":                              "El último deseo de Yaakov",
"vol2/seccion-034-the-blessing-of-ephraim-and-manasseh.md":          "La bendición de Efraím y Menashé",
"vol2/seccion-035-the-blessing-of-the-twelve-tribes.md":             "La bendición de las doce tribus",
"vol2/seccion-036-the-death-of-jacob.md":                            "La muerte de Yaakov",
"vol2/seccion-037-the-sons-of-jacob-at-war-with-the-sons-of-esau.md": "Los hijos de Yaakov en guerra con los hijos de Esav",
"vol2/seccion-038-zepho-king-of-kittim.md":                         "Tsefó, rey de Kitím",
"vol2/seccion-039-the-nations-at-war.md":                            "Las naciones en guerra",
"vol2/seccion-040-josephs-magnanimity.md":                           "La magnanimidad de Yosef",
"vol2/seccion-041-asenath.md":                                        "Asnat",
"vol2/seccion-042-the-marriage-of-joseph.md":                        "El matrimonio de Yosef",
"vol2/seccion-043-kind-and-unkind-brethren.md":                      "Hermanos bondadosos y hermanos crueles",
"vol2/seccion-044-treachery-punished.md":                            "La traición castigada",
"vol2/seccion-045-the-death-and-burial-of-joseph.md":                "La muerte y sepultura de Yosef",
"vol2/seccion-046-significant-names.md":                             "Nombres significativos",
"vol2/seccion-047-reubens-testament.md":                             "El testamento de Reuvén",
"vol2/seccion-048-simons-admonition-against-envy.md":                "La admonición de Shimón contra la envidia",
"vol2/seccion-049-the-ascension-of-levi.md":                         "La ascensión de Leví",
"vol2/seccion-050-judah-warns-against-greed-and-unchastity.md":      "Yehudá advierte contra la codicia y la impudicia",
"vol2/seccion-051-issachars-singleness-of-heart.md":                 "La rectitud de corazón de Isajar",
"vol2/seccion-052-zebulon-exhorts-unto-compassion.md":               "Zevulún exhorta a la compasión",
"vol2/seccion-053-dans-confession.md":                               "La confesión de Dan",
"vol2/seccion-054-naphtalis-dreams-of-the-division-of-the-tribes.md": "Los sueños de Naftalí sobre la división de las tribus",
"vol2/seccion-055-gads-hatred.md":                                   "El odio de Gad",
"vol2/seccion-056-ashers-last-words.md":                             "Las últimas palabras de Asher",
"vol2/seccion-057-benjamin-extols-joseph.md":                        "Binyamín ensalza a Yosef",
"vol2/seccion-058-job-and-the-patriarchs.md":                        "Job y los Patriarcas",
"vol2/seccion-059-jobs-wealth-and-benefactions.md":                  "La riqueza y las obras benéficas de Job",
"vol2/seccion-060-satan-and-job.md":                                 "Satán y Job",
"vol2/seccion-061-jobs-suffering.md":                                "Los padecimientos de Job",
"vol2/seccion-062-the-four-friends.md":                              "Los cuatro amigos",
"vol2/seccion-063-job-restored.md":                                  "La restauración de Job",
"vol2/seccion-064-the-beginning-of-the-egyptian-bondage.md":         "El comienzo de la esclavitud en Egipto",
"vol2/seccion-065-pharaohs-cunning.md":                              "La astucia del Faraón",
"vol2/seccion-066-the-pious-midwives.md":                            "Las parteras piadosas",
"vol2/seccion-067-the-three-counsellors.md":                         "Los tres consejeros",
"vol2/seccion-068-the-slaughter-of-the-innocents.md":                "La matanza de los inocentes",
"vol2/seccion-069-the-parents-of-moses.md":                          "Los padres de Moshé",
"vol2/seccion-070-the-birth-of-moses.md":                            "El nacimiento de Moshé",
"vol2/seccion-071-moses-rescued-from-the-water.md":                  "Moshé rescatado de las aguas",
"vol2/seccion-072-the-infancy-of-moses.md":                          "La infancia de Moshé",
"vol2/seccion-073-moses-rescued-by-gabriel.md":                      "Moshé salvado por Gavriel",
"vol2/seccion-074-the-youth-of-moses.md":                            "La juventud de Moshé",
"vol2/seccion-075-the-flight.md":                                    "La huida",
"vol2/seccion-076-the-king-of-ethiopia.md":                          "El rey de Etiopía",
"vol2/seccion-077-jethro.md":                                        "Yitró",
"vol2/seccion-078-moses-marries-zipporah.md":                        "Moshé desposa a Tziporá",
"vol2/seccion-079-a-bloody-remedy.md":                               "Un remedio sangriento",
"vol2/seccion-080-the-faithful-shepherd.md":                         "El pastor fiel",
"vol2/seccion-081-the-burning-thorn-bush.md":                        "La zarza ardiente",
"vol2/seccion-082-the-ascension-of-moses.md":                        "La ascensión de Moshé",
"vol2/seccion-083-moses-visits-paradise-and-hell.md":                "Moshé visita el Paraíso y el Guehinom",
"vol2/seccion-084-moses-declines-the-mission.md":                    "Moshé rechaza la misión",
"vol2/seccion-085-moses-punished-for-his-stubbornness.md":           "Moshé castigado por su obstinación",
"vol2/seccion-086-the-return-to-egypt.md":                           "El regreso a Egipto",
"vol2/seccion-087-moses-and-aaron-before-pharaoh.md":                "Moshé y Aharón ante el Faraón",
"vol2/seccion-088-the-suffering-increases.md":                       "El sufrimiento se acrecienta",
"vol2/seccion-089-measure-for-measure.md":                           "Medida por medida",
"vol2/seccion-090-the-plagues-brought-through-aaron.md":             "Las plagas ejecutadas por medio de Aharón",
"vol2/seccion-091-the-plagues-brought-through-moses.md":             "Las plagas ejecutadas por medio de Moshé",
"vol2/seccion-092-the-first-passover.md":                            "El primer Pésaj",
"vol2/seccion-093-the-smiting-of-the-first-born.md":                 "La muerte de los primogénitos",
"vol2/seccion-094-the-redemption-of-israel-from-egyptian-bondage.md": "La redención de Israel de la esclavitud egipcia",
"vol2/seccion-095-the-exodus.md":                                    "El Éxodo",

# ════════════════════════════════════════════════════════
# VOL 3  (sin índice previo — traducción siguiendo criterios del proyecto)
# ════════════════════════════════════════════════════════
"vol3/seccion-004-the-long-route.md":                                "La ruta larga",
"vol3/seccion-005-pharaoh-pursues-the-hebrews.md":                   "El Faraón persigue a los hebreos",
"vol3/seccion-006-the-sea-divided.md":                               "El mar dividido",
"vol3/seccion-007-the-passage-through-the-red-sea.md":               "El paso a través del Mar Rojo",
"vol3/seccion-008-the-destruction-of-the-egyptians.md":              "La destrucción de los egipcios",
"vol3/seccion-009-the-song-at-the-sea.md":                           "El cántico en el mar",
"vol3/seccion-010-the-awful-desert.md":                              "El terrible desierto",
"vol3/seccion-011-the-heavenly-food.md":                             "El alimento celestial",
"vol3/seccion-012-the-gathering-of-the-manna.md":                    "La recogida del maná",
"vol3/seccion-013-miriams-well.md":                                  "El pozo de Miriam",
"vol3/seccion-014-amaleks-war-against-israel.md":                    "La guerra de Amalec contra Israel",
"vol3/seccion-015-amalek-defeated.md":                               "Amalec derrotado",
"vol3/seccion-016-jethro.md":                                        "Yitró",
"vol3/seccion-017-the-installation-of-elders.md":                    "La institución de los ancianos",
"vol3/seccion-018-jethro-rewarded.md":                               "Yitró recompensado",
"vol3/seccion-019-the-time-is-at-hand.md":                           "Ha llegado el momento",
"vol3/seccion-020-the-gentiles-refuse-the-torah.md":                 "Los gentiles rechazan la Torá",
"vol3/seccion-021-the-contest-of-the-mountains.md":                  "La disputa de las montañas",
"vol3/seccion-022-the-torah-offered-to-israel.md":                   "La Torá ofrecida a Israel",
"vol3/seccion-023-israel-prepares-for-the-revelation.md":            "Israel se prepara para la revelación",
"vol3/seccion-024-the-revelation-on-mount-sinai.md":                 "La revelación en el monte Sinaí",
"vol3/seccion-025-the-first-commandment.md":                         "El primer mandamiento",
"vol3/seccion-026-the-other-commandments-revealed-on-sinai.md":      "Los demás mandamientos revelados en el Sinaí",
"vol3/seccion-027-the-unity-of-the-ten-commandments.md":             "La unidad de los Diez Mandamientos",
"vol3/seccion-028-moses-chosen-as-intermediator.md":                 "Moshé elegido como intermediario",
"vol3/seccion-029-moses-and-the-angels-strive-for-the-torah.md":     "Moshé y los ángeles se disputan la Torá",
"vol3/seccion-030-moses-receives-the-torah.md":                      "Moshé recibe la Torá",
"vol3/seccion-031-the-golden-calf.md":                               "El becerro de oro",
"vol3/seccion-032-moses-blamed-for-israels-sin.md":                  "Moshé culpado por el pecado de Israel",
"vol3/seccion-033-the-punishment-of-the-sinners.md":                 "El castigo de los pecadores",
"vol3/seccion-034-moses-intercedes-for-the-people.md":               "Moshé intercede por el pueblo",
"vol3/seccion-035-the-inscrutable-ways-of-the-lord.md":              "Los caminos insondables del Eterno",
"vol3/seccion-036-the-thirteen-attributes-of-god.md":                "Los trece atributos del Eterno",
"vol3/seccion-037-the-second-tables.md":                             "Las segundas tablas",
"vol3/seccion-038-the-census-of-the-people.md":                      "El censo del pueblo",
"vol3/seccion-039-the-erection-of-the-tabernacle-commanded.md":      "La orden de erigir el Tabernáculo",
"vol3/seccion-040-the-materials-for-the-construction-of-the-tabernacle.md": "Los materiales para la construcción del Tabernáculo",
"vol3/seccion-041-bezalel.md":                                        "Betzalel",
"vol3/seccion-042-the-ark-with-the-cherubim.md":                     "El Arca con los querubines",
"vol3/seccion-043-the-table-and-the-candlestick.md":                 "La mesa y el candelabro",
"vol3/seccion-044-the-altar.md":                                      "El altar",
"vol3/seccion-045-the-symbolical-significance-of-the-tabernacle.md": "El significado simbólico del Tabernáculo",
"vol3/seccion-046-the-priestly-robes.md":                            "Las vestiduras sacerdotales",
"vol3/seccion-047-the-stones-in-the-breastplate.md":                 "Las piedras en el pectoral",
"vol3/seccion-048-the-completion-of-the-tabernacle.md":              "La conclusión del Tabernáculo",
"vol3/seccion-049-the-setting-up-of-the-tabernacle.md":              "La erección del Tabernáculo",
"vol3/seccion-050-the-consecration-of-the-priests.md":               "La consagración de los sacerdotes",
"vol3/seccion-051-the-day-of-the-ten-crowns.md":                     "El día de las diez coronas",
"vol3/seccion-052-the-interrupted-joy.md":                           "La alegría interrumpida",
"vol3/seccion-053-the-gifts-of-the-princes.md":                      "Los dones de los príncipes",
"vol3/seccion-054-the-revelations-in-the-tabernacle.md":             "Las revelaciones en el Tabernáculo",
"vol3/seccion-055-the-cleansing-of-the-camp.md":                     "La purificación del campamento",
"vol3/seccion-056-the-lighting-of-the-candlestick.md":               "El encendido del candelabro",
"vol3/seccion-057-the-twelve-princes-of-the-tribes.md":              "Los doce príncipes de las tribus",
"vol3/seccion-058-the-census-of-the-levites.md":                     "El censo de los levitas",
"vol3/seccion-059-the-four-divisions-of-the-levites.md":             "Las cuatro divisiones de los levitas",
"vol3/seccion-060-the-four-standards.md":                            "Las cuatro banderas",
"vol3/seccion-061-the-camp.md":                                       "El campamento",
"vol3/seccion-062-the-blasphemer-and-the-sabbath-breaker.md":        "El blasfemo y el violador del Shabat",
"vol3/seccion-063-the-ungrateful-multitude.md":                      "La multitud ingrata",
"vol3/seccion-064-the-flesh-pots-of-egypt.md":                       "Las ollas de carne de Egipto",
"vol3/seccion-065-the-appointment-of-the-seventy-elders.md":         "El nombramiento de los setenta ancianos",
"vol3/seccion-066-eldad-and-medad.md":                               "Eldad y Medad",
"vol3/seccion-067-the-quails.md":                                     "Las codornices",
"vol3/seccion-068-aaron-and-miriam-slander-moses.md":                "Aharón y Miriam calumnian a Moshé",
"vol3/seccion-069-miriams-punishment.md":                            "El castigo de Miriam",
"vol3/seccion-070-the-sending-of-the-spies.md":                      "El envío de los espías",
"vol3/seccion-071-significant-names.md":                             "Nombres significativos",
"vol3/seccion-072-the-spies-in-palestine.md":                        "Los espías en Palestina",
"vol3/seccion-073-the-slanderous-report.md":                         "El informe calumnioso",
"vol3/seccion-074-the-night-of-tears.md":                            "La noche de las lágrimas",
"vol3/seccion-075-ingratitude-punished.md":                          "La ingratitud castigada",
"vol3/seccion-076-the-years-of-disfavor.md":                         "Los años de desgracia",
"vol3/seccion-077-the-rebellion-of-korah.md":                        "La rebelión de Koraj",
"vol3/seccion-078-korah-abuses-moses-and-the-torah.md":              "Koraj ultraja a Moshé y a la Torá",
"vol3/seccion-079-moses-pleads-in-vain-with-korah.md":               "Moshé suplica en vano a Koraj",
"vol3/seccion-080-korah-and-his-horde-punished.md":                  "Koraj y su horda castigados",
"vol3/seccion-081-on-and-the-three-sons-of-korah-saved.md":          "On y los tres hijos de Koraj salvados",
"vol3/seccion-082-israel-convinced-of-aarons-priesthood.md":         "Israel se convence del sacerdocio de Aharón",
"vol3/seccion-083-the-waters-of-meribah.md":                         "Las aguas de Meribá",
"vol3/seccion-084-moses-anger-causes-his-doom.md":                   "La ira de Moshé causa su condena",
"vol3/seccion-085-edoms-unbrotherly-attitude-toward-israel.md":      "La actitud poco fraterna de Edom hacia Israel",
"vol3/seccion-086-the-three-shepherds.md":                           "Los tres pastores",
"vol3/seccion-087-preparing-aaron-for-impending-death.md":           "Preparando a Aharón para la muerte inminente",
"vol3/seccion-088-aarons-death.md":                                  "La muerte de Aharón",
"vol3/seccion-089-the-general-mourning-for-aaron.md":                "El luto general por Aharón",
"vol3/seccion-090-the-false-friends.md":                             "Los falsos amigos",
"vol3/seccion-091-the-brazen-serpent.md":                            "La serpiente de bronce",
"vol3/seccion-092-at-arnon.md":                                       "En Arnón",
"vol3/seccion-093-sihon-the-king-of-the-amorites.md":               "Sijón, el rey de los amorreos",
"vol3/seccion-094-the-giant-og.md":                                   "El gigante Og",
"vol3/seccion-095-moses-speech-of-admonition.md":                    "El discurso de admonición de Moshé",
"vol3/seccion-096-balak-king-of-moab.md":                            "Balak, rey de Moab",
"vol3/seccion-097-balaam-the-heathen-prophet.md":                    "Bilam, el profeta pagano",
"vol3/seccion-098-balaks-messengers-to-balaam.md":                   "Los mensajeros de Balak a Bilam",
"vol3/seccion-099-balaam-accepts-balaks-invitation.md":              "Bilam acepta la invitación de Balak",
"vol3/seccion-100-balaams-ass.md":                                    "La asna de Bilam",
"vol3/seccion-101-balaam-runs-into-his-own-destruction.md":          "Bilam corre hacia su propia destrucción",
"vol3/seccion-102-balaam-with-balak.md":                             "Bilam con Balak",
"vol3/seccion-103-balaams-sacrifices-refused.md":                    "Los sacrificios de Bilam rechazados",
"vol3/seccion-104-balaam-extols-israel.md":                          "Bilam ensalza a Israel",
"vol3/seccion-105-balaams-hopes-disappointed.md":                    "Las esperanzas de Bilam frustradas",
"vol3/seccion-106-curses-turned-to-blessings.md":                    "Las maldiciones convertidas en bendiciones",
"vol3/seccion-107-balaams-wicked-counsel.md":                        "El perverso consejo de Bilam",
"vol3/seccion-108-phinehas-zealous-for-god.md":                      "Pinjas, celoso por el Eterno",
"vol3/seccion-109-twelve-miracles.md":                               "Doce milagros",
"vol3/seccion-110-phinehas-rewarded.md":                             "Pinjas recompensado",
"vol3/seccion-111-the-daughters-of-zelophehad.md":                   "Las hijas de Tzelofejad",
"vol3/seccion-112-the-appointment-of-joshua.md":                     "El nombramiento de Yehoshúa",
"vol3/seccion-113-moses-legacy-to-joshua.md":                        "El legado de Moshé a Yehoshúa",
"vol3/seccion-114-moses-last-campaign.md":                           "La última campaña de Moshé",
"vol3/seccion-115-the-complete-annihilation-of-midian.md":           "El exterminio completo de Midián",
"vol3/seccion-116-the-gruesome-end-of-balaam.md":                    "El espantoso fin de Bilam",
"vol3/seccion-117-the-victorious-return-from-the-war.md":            "El regreso victorioso de la guerra",
"vol3/seccion-118-wealth-that-bringeth-destruction.md":              "La riqueza que trae destrucción",
"vol3/seccion-119-moses-death-irrevocably-doomed.md":                "La muerte de Moshé, irrevocablemente sellada",
"vol3/seccion-120-moses-prayer-for-suspension-of-judgment.md":       "La plegaria de Moshé para suspender el juicio",
"vol3/seccion-121-god-tries-to-comfort-moses-concerning-his-death.md": "El Eterno intenta consolar a Moshé ante su muerte",
"vol3/seccion-122-the-intercessions-for-moses.md":                   "Las intercesiones en favor de Moshé",
"vol3/seccion-123-moses-serves-joshua.md":                           "Moshé sirve a Yehoshúa",
"vol3/seccion-124-the-last-day-of-moses-life.md":                    "El último día de la vida de Moshé",
"vol3/seccion-125-moses-beholds-the-future.md":                      "Moshé contempla el futuro",
"vol3/seccion-126-moses-meets-the-messiah-in-heaven.md":             "Moshé se encuentra con el Mashíaj en el cielo",
"vol3/seccion-127-the-last-hours-of-moses.md":                       "Las últimas horas de Moshé",
"vol3/seccion-128-the-blessing-of-moses.md":                         "La bendición de Moshé",
"vol3/seccion-129-moses-prays-for-death.md":                         "Moshé suplica la muerte",
"vol3/seccion-130-samael-chastised-by-moses.md":                     "Samaél reprendido por Moshé",
"vol3/seccion-131-god-kisses-moses-soul.md":                         "El Eterno besa el alma de Moshé",
"vol3/seccion-132-the-mourning-for-moses.md":                        "El duelo por Moshé",
"vol3/seccion-133-samaels-vain-search.md":                           "La vana búsqueda de Samaél",
"vol3/seccion-134-moses-excels-all-pious-men.md":                    "Moshé supera a todos los hombres piadosos",

# ════════════════════════════════════════════════════════
# VOL 4
# ════════════════════════════════════════════════════════
"vol4/seccion-014-the-servant-of-moses.md":                          "El siervo de Moshé",
"vol4/seccion-015-entering-the-promised-land.md":                    "La entrada en la Tierra Prometida",
"vol4/seccion-016-conquest-of-the-land.md":                         "La conquista de la Tierra",
"vol4/seccion-017-the-sun-obeys-joshua.md":                          "El sol obedece a Yehoshúa",
"vol4/seccion-018-war-with-the-armenians.md":                        "La guerra con los armenios",
"vol4/seccion-019-allotment-of-the-land.md":                        "El reparto de la Tierra",
"vol4/seccion-020-the-first-judge.md":                               "El primer juez",
"vol4/seccion-021-campaigns-of-kenaz.md":                            "Las campañas de Kenaz",
"vol4/seccion-022-othniel.md":                                        "Otniel",
"vol4/seccion-023-boaz-and-ruth.md":                                 "Boaz y Rut",
"vol4/seccion-024-deborah.md":                                        "Devorá",
"vol4/seccion-025-gideon.md":                                         "Gedeón",
"vol4/seccion-026-jephthah.md":                                       "Yiftaj",
"vol4/seccion-027-samson.md":                                         "Shimshón",
"vol4/seccion-028-the-crime-of-the-benjamites.md":                   "El crimen de los benjaminitas",
"vol4/seccion-029-elkanah-and-hannah.md":                            "Elcaná y Janá",
"vol4/seccion-030-the-youth-of-samuel.md":                           "La juventud de Samuel",
"vol4/seccion-031-eli-and-his-sons.md":                              "Elí y sus hijos",
"vol4/seccion-032-the-activities-of-samuel.md":                      "Las obras de Samuel",
"vol4/seccion-033-the-reign-of-saul.md":                             "El reinado de Saúl",
"vol4/seccion-034-the-court-of-saul.md":                             "La corte de Saúl",
"vol4/seccion-035-davids-birth-and-descent.md":                      "Nacimiento y linaje de David",
"vol4/seccion-036-anointed-king.md":                                  "Ungido como rey",
"vol4/seccion-037-encounter-with-goliath.md":                        "El encuentro con Goliat",
"vol4/seccion-038-pursued-by-saul.md":                               "Perseguido por Shaúl",
"vol4/seccion-039-wars.md":                                           "Guerras",
"vol4/seccion-040-ahithophel.md":                                     "Ajitofel",
"vol4/seccion-041-joab.md":                                           "Yoav",
"vol4/seccion-042-davids-piety-and-his-sin.md":                      "La piedad de David y su pecado",
"vol4/seccion-043-absaloms-rebellion.md":                            "La rebelión de Avshalom",
"vol4/seccion-044-davids-atonement.md":                              "La expiación de David",
"vol4/seccion-045-visitations.md":                                    "Tribulaciones",
"vol4/seccion-046-the-death-of-david.md":                            "La muerte de David",
"vol4/seccion-047-david-in-paradise.md":                             "David en el Paraíso",
"vol4/seccion-048-the-family-of-david.md":                           "La familia de David",
"vol4/seccion-049-his-tomb.md":                                       "Su tumba",
"vol4/seccion-050-solomon-punishes-joab.md":                         "Salomón castiga a Yoav",
"vol4/seccion-051-the-marriage-of-solomon.md":                       "El matrimonio de Salomón",
"vol4/seccion-052-his-wisdom.md":                                     "Su sabiduría",
"vol4/seccion-053-the-queen-of-sheba.md":                            "La reina de Shevá",
"vol4/seccion-054-solomon-master-of-the-demons.md":                  "Salomón, señor de los demonios",
"vol4/seccion-055-the-building-of-the-temple.md":                    "La construcción del Templo",
"vol4/seccion-056-the-throne-of-solomon.md":                         "El trono de Salomón",
"vol4/seccion-057-the-hippodrome.md":                                 "El hipódromo",
"vol4/seccion-058-lessons-in-humility.md":                           "Lecciones de humildad",
"vol4/seccion-059-asmodeus.md":                                       "Asmodeo",
"vol4/seccion-060-solomon-as-beggar.md":                             "Salomón como mendigo",
"vol4/seccion-061-the-court-of-solomon.md":                          "La corte de Salomón",
"vol4/seccion-062-the-division-of-the-kingdom.md":                   "La división del reino",
"vol4/seccion-063-jeroboam.md":                                       "Yeravam",
"vol4/seccion-064-the-two-abijahs.md":                               "Los dos Ajiyá",
"vol4/seccion-065-asa.md":                                            "Asá",
"vol4/seccion-066-jehoshaphat-and-ahab.md":                          "Yehoshafat y Ajav",
"vol4/seccion-067-jezebel.md":                                        "Izével",
"vol4/seccion-068-joram-of-israel.md":                               "Yoram de Israel",
"vol4/seccion-069-elijah-before-his-translation.md":                 "Eliyahu antes de su traslación",
"vol4/seccion-070-after-his-translation.md":                         "Después de su traslación",
"vol4/seccion-071-censor-and-avenger.md":                            "Censor y vengador",
"vol4/seccion-072-intercourse-with-the-sages.md":                    "Trato con los sabios",
"vol4/seccion-073-gods-justice-vindicated.md":                       "La justicia del Eterno vindicada",
"vol4/seccion-074-elijah-and-the-angel-of-death.md":                 "Eliyahu y el Ángel de la Muerte",
"vol4/seccion-075-teacher-of-the-kabbalah.md":                       "Maestro de la Cabalá",
"vol4/seccion-076-forerunner-of-the-messiah.md":                     "Precursor del Mashíaj",
"vol4/seccion-077-elisha-the-disciple-of-elijah.md":                 "Elishá, el discípulo de Eliyahu",
"vol4/seccion-078-the-shunammite.md":                                 "La sunamita",
"vol4/seccion-079-gehazi.md":                                         "Guejazí",
"vol4/seccion-080-the-flight-of-jonah.md":                           "La huida de Yoná",
"vol4/seccion-081-jonah-in-the-whale.md":                            "Yoná en el interior de la ballena",
"vol4/seccion-082-the-repentance-of-nineveh.md":                     "El arrepentimiento de Nínive",
"vol4/seccion-083-joash.md":                                          "Yoash",
"vol4/seccion-084-three-great-prophets.md":                          "Tres grandes profetas",
"vol4/seccion-085-the-two-kingdoms-chastised.md":                    "Los dos reinos castigados",
"vol4/seccion-086-hezekiah.md":                                       "Jizkiyahu",
"vol4/seccion-087-miracles-wrought-for-hezekiah.md":                 "Milagros obrados en favor de Jizkiyahu",
"vol4/seccion-088-manasseh.md":                                       "Menashé",
"vol4/seccion-089-josiah-and-his-successors.md":                     "Yoshiyahu y sus sucesores",
"vol4/seccion-090-zedekiah.md":                                       "Tzidkiyahu",
"vol4/seccion-091-jeremiah.md":                                       "Yirmeyahu",
"vol4/seccion-092-nebuchadnezzar.md":                                 "Nevujadnetzar",
"vol4/seccion-093-the-capture-of-jerusalem.md":                      "La captura de Yerushaláyim",
"vol4/seccion-094-the-great-lament.md":                              "El gran lamento",
"vol4/seccion-095-jeremiahs-journey-to-babylon.md":                  "El viaje de Yirmeyahu a Babilonia",
"vol4/seccion-096-transportation-of-the-captives.md":                "El traslado de los cautivos",
"vol4/seccion-097-the-sons-of-moses.md":                             "Los hijos de Moshé",
"vol4/seccion-098-ebed-melech.md":                                    "Eved-Mélej",
"vol4/seccion-099-the-temple-vessels.md":                            "Los utensilios del Templo",
"vol4/seccion-100-baruch.md":                                         "Baruj",
"vol4/seccion-101-the-tombs-of-baruch-and-ezekiel.md":               "Las tumbas de Baruj y Yejezkel",
"vol4/seccion-102-daniel.md":                                         "Daniel",
"vol4/seccion-103-the-three-men-in-the-furnace.md":                  "Los tres hombres en el horno",
"vol4/seccion-104-ezekiel-revives-the-dead.md":                      "Yejezkel resucita a los muertos",
"vol4/seccion-105-nebuchadnezzar-a-beast.md":                        "Nevujadnetzar convertido en bestia",
"vol4/seccion-106-hiram.md":                                          "Jirám",
"vol4/seccion-107-the-false-prophets.md":                            "Los falsos profetas",
"vol4/seccion-108-daniels-piety.md":                                  "La piedad de Daniel",
"vol4/seccion-109-belshazzars-feast.md":                             "La fiesta de Baltasar",
"vol4/seccion-110-daniel-under-the-persian-kings.md":                "Daniel bajo los reyes persas",
"vol4/seccion-111-the-grave-of-daniel.md":                           "La tumba de Daniel",
"vol4/seccion-112-zerubbabel.md":                                     "Zorobabel",
"vol4/seccion-113-ezra.md":                                           "Esdras",
"vol4/seccion-114-the-men-of-the-great-assembly.md":                 "Los hombres de la Gran Asamblea",
"vol4/seccion-115-the-feast-for-the-grandees.md":                    "El banquete para los magnates",
"vol4/seccion-116-the-festivities-in-shushan.md":                    "Las festividades en Shushán",
"vol4/seccion-117-vasthis-banquet.md":                               "El banquete de Vashtí",
"vol4/seccion-118-the-fate-of-vashti.md":                            "El destino de Vashtí",
"vol4/seccion-119-the-follies-of-ahasuerus.md":                      "Las insensateces de Ajashverosh",
"vol4/seccion-120-mordecai.md":                                       "Mordejai",
"vol4/seccion-121-esthers-beauty-and-piety.md":                      "La belleza y la piedad de Ester",
"vol4/seccion-122-the-conspiracy.md":                                 "La conspiración",
"vol4/seccion-123-haman-the-jew-baiter.md":                          "Hamán, el hostigador de judíos",
"vol4/seccion-124-mordecais-pride.md":                               "El orgullo de Mordejai",
"vol4/seccion-125-casting-the-lots.md":                              "El sorteo de las suertes",
"vol4/seccion-126-the-denunciation-of-the-jews.md":                  "La denuncia contra los judíos",
"vol4/seccion-127-the-decree-of-annihilation.md":                    "El decreto de aniquilación",
"vol4/seccion-128-satan-indicts-the-jews.md":                        "Satán acusa a los judíos",
"vol4/seccion-129-the-dream-of-mordecai-fulfilled.md":               "El sueño de Mordejai se cumple",
"vol4/seccion-130-the-prayer-of-esther.md":                          "La plegaria de Ester",
"vol4/seccion-131-esther-intercedes.md":                             "Ester intercede",
"vol4/seccion-132-the-disturbed-night.md":                           "La noche turbada",
"vol4/seccion-133-the-fall-of-haman.md":                             "La caída de Hamán",
"vol4/seccion-134-the-edict-of-the-king.md":                         "El edicto del rey",
}

changed = 0
skipped = 0
for rel_path, nuevo_titulo in TITULOS.items():
    fpath = os.path.join(BASE, rel_path)
    if not os.path.exists(fpath):
        print(f"  ⚠ NO EXISTE: {rel_path}")
        skipped += 1
        continue
    with open(fpath, 'r', encoding='utf-8') as f:
        lines = f.readlines()
    if not lines:
        continue
    nueva_h1 = f"# {nuevo_titulo}\n"
    if lines[0] == nueva_h1:
        continue  # ya correcto
    lines[0] = nueva_h1
    with open(fpath, 'w', encoding='utf-8') as f:
        f.writelines(lines)
    changed += 1

print(f"\nArchivos actualizados: {changed}")
print(f"No encontrados: {skipped}")
